### ISSUE TITLE
ghub+ incompatible with new apiwrap?

### ISSUE THREAD

**Issue by stardiviner** [vermiculus/ghub-plus#8]
I have this error after upgrade `apiwrap`
```
Debugger entered--Lisp error: (error ":condition-case must be a list of error handlers; see the documentation: ((ghub-404 nil) (ghub-http-error (if (eq it 404) (progn nil) (signal (car it) (cdr it)))))")
  signal(error (":condition-case must be a list of error handlers; see the documentation: ((ghub-404 nil) (ghub-http-error (if (eq it 404) (progn nil) (signal (car it) (cdr it)))))"))
  error(":condition-case must be a list of error handlers; see the documentation: %S" ((ghub-404 nil) (ghub-http-error (if (eq it 404) (progn nil) (signal (car it) (cdr it))))))
  apiwrap-gendefun("GitHub" "ghubp" ((repo . "REPO is a repository alist of the form returned by `ghubp-get-user-repos'.") (branch . "BRANCH is a branch object of the form returned by `ghubp-get-repos-owner-repo-branches-branch'.") (org . "ORG is an organization alist of the form returned by `ghubp-get-user-orgs'.") (thread . "THREAD is a thread object of the form returned by `ghubp-get-repos-owner-repo-comments'.") (issue . "ISSUE is an issue object of the form returned by `ghubp-get-issues'.") (pull-request . "PULL-REQUEST is a pull request object of the form returned by `ghubp-get-repos-owner-repo-pulls'.") (review . "REVIEW is a review object of the form returned by `ghubp-get-repos-owner-repo-pulls-number-reviews'.") (label . "LABEL is a label object of the form returned by `ghubp-get-repos-owner-repo-issues-number-labels'.") (ref . "REF is a string and can be a SHA, a branch name, or a tag name.") (milestone . "MILESTONE is a milestone object.") (user . "USER is a user object.") (user-1 . "USER-1 is a user object.") (user-2 . "USER-2 is a user object.") (key . "KEY is a key object.")) get "/repos/:owner/:repo" "Get a specific repository object." "repos/#get" (repo) "/repos/:repo.owner.login/:repo.name" ((pre-process-params . ghubp--pre-process-params) (link . ghubp--make-link) (request . ghubp-request)) (:condition-case (ghubp-catch (404 nil))))
  (lambda (resource doc link &optional objects internal-resource &rest config) "Define a new GET resource wrapper function.\n\nRESOURCE is the API endpoint as written in the GitHub API\ndocumentation.  Along with the backend prefix (from\n`apiwrap-new-backend') and the method (GET), this string will be\nused to create the symbol for the new function.\n\nDOC is a specific documentation string for the new function.\nUsually, this can be copied from the GitHub API documentation.\n\nLINK is a link to the GitHub API documentation.\n\nIf non-nil, OBJECTS is a list of symbols that will be used to\nresolve parameters in the resource and will be required arguments\nof the new function.  Documentation for these parameters (from\nthe standard parameters of the call to `apiwrap-new-backend')\nwill be inserted into the docstring of the generated function.\n\nIf non-nil, INTERNAL-RESOURCE is the resource-string used to\nresolve OBJECT to the ultimate call instead of RESOURCE.  This is\nuseful in the likely event that the advertised resource syntax\ndoes not align with the structure of the object it works with.\nFor example, GitHub's endpoint\n\n    GET /repos/:owner/:repo/issues\n\nwould be written as\n\n    (defapiget-<prefix> \"/repos/:owner/:repo/issues\"\n      \"List issues for a repository.\"\n      \"issues/#list-issues-for-a-repository\"\n      (repo) \"/repos/:repo.owner.login/:repo.name/issues\")\n\ndefining a function called `<prefix>-get-repos-owner-repo-issues'\nand taking an object (a parameter called `repo') with the\nstructure\n\n    ((owner (login . \"octocat\"))\n     (name . \"hello-world\")\n\nSee the documentation of `apiwrap-resolve-api-params' for more\ndetails on that behavior.\n\nCONFIG is a list of override configuration parameters.  Values\nset here (notably those explicitly set to nil) will take\nprecedence over the defaults provided to `apiwrap-new-backend'." (apiwrap-gendefun "GitHub" "ghubp" '((repo . "REPO is a repository alist of the form returned by `ghubp-get-user-repos'.") (branch . "BRANCH is a branch object of the form returned by `ghubp-get-repos-owner-repo-branches-branch'.") (org . "ORG is an organization alist of the form returned by `ghubp-get-user-orgs'.") (thread . "THREAD is a thread object of the form returned by `ghubp-get-repos-owner-repo-comments'.") (issue . "ISSUE is an issue object of the form returned by `ghubp-get-issues'.") (pull-request . "PULL-REQUEST is a pull request object of the form returned by `ghubp-get-repos-owner-repo-pulls'.") (review . "REVIEW is a review object of the form returned by `ghubp-get-repos-owner-repo-pulls-number-reviews'.") (label . "LABEL is a label object of the form returned by `ghubp-get-repos-owner-repo-issues-number-labels'.") (ref . "REF is a string and can be a SHA, a branch name, or a tag name.") (milestone . "MILESTONE is a milestone object.") (user . "USER is a user object.") (user-1 . "USER-1 is a user object.") (user-2 . "USER-2 is a user object.") (key . "KEY is a key object.")) 'get resource doc link objects internal-resource '((pre-process-params . ghubp--pre-process-params) (link . ghubp--make-link) (request . ghubp-request)) config))("/repos/:owner/:repo" "Get a specific repository object." "repos/#get" (repo) "/repos/:repo.owner.login/:repo.name" :condition-case (ghubp-catch (404 nil)))
  (defapiget-ghubp "/repos/:owner/:repo" "Get a specific repository object." "repos/#get" (repo) "/repos/:repo.owner.login/:repo.name" :condition-case (ghubp-catch (404 nil)))
  eval-buffer(#<buffer  *load*-231992> nil "/home/stardiviner/.emacs.d/elpa/ghub+-20180318.1518/ghub+.el" nil t)  ; Reading at buffer position 29687
  load-with-code-conversion("/home/stardiviner/.emacs.d/elpa/ghub+-20180318.1518/ghub+.el" "/home/stardiviner/.emacs.d/elpa/ghub+-20180318.1518/ghub+.el" t t)
  require(ghub+ nil t)
  (not (require 'ghub+ nil t))
  (if (not (require 'ghub+ nil t)) (display-warning 'use-package (format "Cannot load %s" 'ghub+) :error) (let ((now (current-time))) (message "%s..." "Configuring package ghub+") (prog1 (condition-case err (progn (defvar github-notifications-number nil) (defalias 'github-fetch-notifications (function (lambda nil (if (my:internet-network-available\?) (progn (setq github-notifications-number (length (ghubp-get-notifications :participating "true")))))))) (run-with-timer 10 (* 10 60) 'github-fetch-notifications) (defalias '*github-notifications (function (lambda nil (if (and (mode-line-window-active-p) (> github-notifications-number 0)) (propertize (concat (all-the-icons-faicon "github" :v-adjust 0.05) (format " %s " github-notifications-number)) 'face 'mode-line-data-face))))) (defalias 'github-open-notifications-participating (function (lambda nil "Open GitHub Notifications/Participating page." (interactive) (browse-url "https://github.com/notifications/participating")))) (if (boundp 'prog-vcs-prefix) nil (define-prefix-command 'prog-vcs-prefix)) (define-key prog-vcs-prefix (kbd "N") 'github-open-notifications-participating) t) ((debug error) (funcall use-package--warning47 :config err))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package ghub+" elapsed) (message "%s...done" "Configuring package ghub+"))))))
  (prog1 (if (not (require 'ghub+ nil t)) (display-warning 'use-package (format "Cannot load %s" 'ghub+) :error) (let ((now (current-time))) (message "%s..." "Configuring package ghub+") (prog1 (condition-case err (progn (defvar github-notifications-number nil) (defalias 'github-fetch-notifications (function (lambda nil (if (my:internet-network-available\?) (progn (setq github-notifications-number (length (ghubp-get-notifications :participating "true")))))))) (run-with-timer 10 (* 10 60) 'github-fetch-notifications) (defalias '*github-notifications (function (lambda nil (if (and (mode-line-window-active-p) (> github-notifications-number 0)) (propertize (concat (all-the-icons-faicon "github" :v-adjust 0.05) (format " %s " github-notifications-number)) 'face 'mode-line-data-face))))) (defalias 'github-open-notifications-participating (function (lambda nil "Open GitHub Notifications/Participating page." (interactive) (browse-url "https://github.com/notifications/participating")))) (if (boundp 'prog-vcs-prefix) nil (define-prefix-command 'prog-vcs-prefix)) (define-key prog-vcs-prefix (kbd "N") 'github-open-notifications-participating) t) ((debug error) (funcall use-package--warning47 :config err))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package ghub+" elapsed) (message "%s...done" "Configuring package ghub+")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package ghub+" elapsed) (message "%s...done" "Loading package ghub+"))))
  (let ((now (current-time))) (message "%s..." "Loading package ghub+") (prog1 (if (not (require 'ghub+ nil t)) (display-warning 'use-package (format "Cannot load %s" 'ghub+) :error) (let ((now (current-time))) (message "%s..." "Configuring package ghub+") (prog1 (condition-case err (progn (defvar github-notifications-number nil) (defalias 'github-fetch-notifications (function (lambda nil (if (my:internet-network-available\?) (progn (setq github-notifications-number (length (ghubp-get-notifications :participating "true")))))))) (run-with-timer 10 (* 10 60) 'github-fetch-notifications) (defalias '*github-notifications (function (lambda nil (if (and (mode-line-window-active-p) (> github-notifications-number 0)) (propertize (concat (all-the-icons-faicon "github" :v-adjust 0.05) (format " %s " github-notifications-number)) 'face 'mode-line-data-face))))) (defalias 'github-open-notifications-participating (function (lambda nil "Open GitHub Notifications/Participating page." (interactive) (browse-url "https://github.com/notifications/participating")))) (if (boundp 'prog-vcs-prefix) nil (define-prefix-command 'prog-vcs-prefix)) (define-key prog-vcs-prefix (kbd "N") 'github-open-notifications-participating) t) ((debug error) (funcall use-package--warning47 :config err))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package ghub+" elapsed) (message "%s...done" "Configuring package ghub+")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package ghub+" elapsed) (message "%s...done" "Loading package ghub+")))))
  (condition-case err (let ((now (current-time))) (message "%s..." "Loading package ghub+") (prog1 (if (not (require 'ghub+ nil t)) (display-warning 'use-package (format "Cannot load %s" 'ghub+) :error) (let ((now (current-time))) (message "%s..." "Configuring package ghub+") (prog1 (condition-case err (progn (defvar github-notifications-number nil) (defalias 'github-fetch-notifications (function (lambda nil (if (my:internet-network-available\?) (progn (setq github-notifications-number (length (ghubp-get-notifications :participating "true")))))))) (run-with-timer 10 (* 10 60) 'github-fetch-notifications) (defalias '*github-notifications (function (lambda nil (if (and (mode-line-window-active-p) (> github-notifications-number 0)) (propertize (concat (all-the-icons-faicon "github" :v-adjust 0.05) (format " %s " github-notifications-number)) 'face 'mode-line-data-face))))) (defalias 'github-open-notifications-participating (function (lambda nil "Open GitHub Notifications/Participating page." (interactive) (browse-url "https://github.com/notifications/participating")))) (if (boundp 'prog-vcs-prefix) nil (define-prefix-command 'prog-vcs-prefix)) (define-key prog-vcs-prefix (kbd "N") 'github-open-notifications-participating) t) ((debug error) (funcall use-package--warning47 :config err))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package ghub+" elapsed) (message "%s...done" "Configuring package ghub+")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package ghub+" elapsed) (message "%s...done" "Loading package ghub+"))))) ((debug error) (funcall use-package--warning47 :catch err)))
  eval-buffer(#<buffer  *load*-752335> nil "/home/stardiviner/.emacs.d/init/Emacs/init-custom-mode-line.el" nil t)  ; Reading at buffer position 39284
  load-with-code-conversion("/home/stardiviner/.emacs.d/init/Emacs/init-custom-mode-line.el" "/home/stardiviner/.emacs.d/init/Emacs/init-custom-mode-line.el" nil t)
  require(init-custom-mode-line)
  eval-buffer(#<buffer  *load*-305378> nil "/home/stardiviner/.emacs.d/init/Emacs/init-emacs-mode-line.el" nil t)  ; Reading at buffer position 191
  load-with-code-conversion("/home/stardiviner/.emacs.d/init/Emacs/init-emacs-mode-line.el" "/home/stardiviner/.emacs.d/init/Emacs/init-emacs-mode-line.el" nil t)
  require(init-emacs-mode-line)
  eval-buffer(#<buffer  *load*> nil "/home/stardiviner/.emacs.d/init.el" nil t)  ; Reading at buffer position 2105
  load-with-code-conversion("/home/stardiviner/.emacs.d/init.el" "/home/stardiviner/.emacs.d/init.el" t t)
  load("/home/stardiviner/.emacs.d/init" noerror nomessage)
  load-user-init-file(#f(compiled-function () #<bytecode 0x25e20d>) #f(compiled-function () #<bytecode 0x25e275>) t)
  command-line()
  normal-top-level()
```

**Comment by vermiculus** [comment]
Did you make sure to update both? I can look into this more later tonight, too.

**Comment by stardiviner** [comment]
Yes, I upgraded all packages.

**Comment by vermiculus** [comment]
Ah, I know what's going on.

To maintain support for old+new versions of ghub, I added handling for both the defunct `ghub-404` error and the generic `ghub-http-error`.

Define `ghub-404` as an error (extended from `ghub-http-error` before loading ghub+ and you should be fine.

I'll see if I can get in touch with Jonas over on magit/ghub to see what his timelines are for release.

**Comment by stardiviner** [comment]
Thanks for quick response. I'm trying to find a workaround way. revert it to emacs work temporarily.

**Comment by tarsius** [comment]
> I'll see if I can get in touch with Jonas over on magit/ghub to see what his timelines are for release.

Tomorrow or the day after. I still have to write a release announcement and in that I want to recommend `magithub`, but for that I still have deal with some issue I have run into in the past.

**Comment by vermiculus** [comment]
This should be fixed by 2a72f9d4a4d023ba37d167b2afc871c6f09f1fa8. Thanks for the report!

I'll keep an eye out for ghub's next release and will remove that kludge when appropriate.

**Comment by jwiegley** [comment]
@vermiculus When building the latest master today, I still see:

```
ghub+.el:794:1:Error: :condition-case must be a list of error handlers; see the documentation: (ghubp-catch* (404 nil))
```

**Comment by vermiculus** [comment]
@jwiegley odd... Why would the compiler see `ghubp-catch*`? Aren't macros expanded at read-time and not compile-time?

**Comment by tohojo** [comment]
I'm seeing the exact same error as @jwiegley when trying to install ghub+ from elpa (as well as when trying the git version)...

**Comment by asheshambasta** [comment]
Same here.

**Comment by vermiculus** [comment]
I'll try to look into this when I'm home, but to be honest I may not; got a lot of wedding stuff to do (two weeks out). If someone can do some investigating I'd be thankful :-)

**Comment by asheshambasta** [comment]
@vermiculus congratulations!

**Comment by vermiculus** [comment]
@asheshambasta thanks! 

I'm not able to reproduce on my machine [nor on CI](https://travis-ci.org/vermiculus/ghub-plus/jobs/384923120), however, [another user](https://gitter.im/vermiculus/magithub?at=5b080868361a950a6614e238) had this issue as well – uninstalling / reinstalling everything seems to fix the issue. Since the solution is heavily dependent on macros, the need to recompile everything is not *too* surprising (though I am surprised this has cropped up so recently for so many people).

Let me know if uninstalling/reinstalling doesn't work 😄

**Comment by tohojo** [comment]
Sean Allred <notifications@github.com> writes:

> @asheshambasta thanks! 
>
> I'm not able to reproduce on my machine [nor on CI](https://travis-ci.org/vermiculus/ghub-plus/jobs/384923120), however, [another user](https://gitter.im/vermiculus/magithub?at=5b080868361a950a6614e238) had this issue as well – uninstalling / reinstalling everything seems to fix the issue. Since the solution is heavily dependent on macros, the need to recompile everything is not *too* surprising (though I am surprised this has cropped up so recently for so many people).
>
> Let me know if uninstalling/reinstalling doesn't work

I just tried running M-x package-delete on both apiwrap and ghub+,
followed by fresh package-install's of both. I still get the same
compilation error on ghub+.

Is there something more I should be doing to get a full reinstall?

I'm running the newly released Emacs 26.1, BTW, if that makes any
difference...

**Comment by vermiculus** [comment]
That should work, but I probably would've deleted all packages (magithub, ghub+, and apiwrap), restarted emacs, and then reinstalled magithub (which will also reinstall the rest).

**Comment by tohojo** [comment]
Sean Allred <notifications@github.com> writes:

> That should work, but I probably would've deleted all packages
> (magithub, ghub+, and apiwrap), restarted emacs, and then reinstalled
> magithub (which will also reinstall the rest).

OK, so I just tried a completely pristine emacs environment. I.e.
`env HOME=$(pwd) emacs -Q`, then running just package-initialize and
adding the melpa repository. And then installing ghub+ and magithub. I
still get the compile errors there, and magithub also fails to run with
the same error.

**Comment by vermiculus** [comment]
I cannot reproduce under `env HOME=$(pwd) emacs -Q` running the following to install magithub:

```elisp
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t))

(package-refresh-contents)
(package-install 'magithub)
```

Starting from magithub's development directory, I'm able to run `magit-status` and get the issues in this repository as expected.  `package.el` compiled ghub+ just fine.

    GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-28

I'm replying to this issue after viewing it with `(magithub-issue-view (magithub-issue (magithub-repo) 8))`.

**Comment by tohojo** [comment]
Sean Allred <notifications@github.com> writes:

> I cannot reproduce under `env HOME=$(pwd) emacs -Q` running the following to install magithub:
>
> ```elisp
> (require 'package)
> (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
>                     (not (gnutls-available-p))))
>        (proto (if no-ssl "http" "https")))
>   (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t))
>
> (package-refresh-contents)
> (package-install 'magithub)
> ```

Aha! This works for me as well; however, in my main config I'm running
with stable.melpa.org, which fails. So I'm guessing there's a bugfix
somewhere that hasn't made it into stable yet?

**Comment by vermiculus** [comment]
Yes, sorry; see vermiculus/magithub#219. Nothing is really 'stable' yet, though I've been making some efforts to fix all that (https://github.com/vermiculus/magithub/commit/8a66e03075ddc59c81d6a18a6a67e6cb7db994cb).

Aaaaand there's your error: https://travis-ci.org/vermiculus/magithub/jobs/384138493#L1112

**Comment by tohojo** [comment]
Sean Allred <notifications@github.com> writes:

> Yes, sorry; see vermiculus/magithub#219. Nothing is really 'stable' yet, though I've been making some efforts to fix all that (https://github.com/vermiculus/magithub/commit/8a66e03075ddc59c81d6a18a6a67e6cb7db994cb).
>
> Aaaaand there's your error:
> https://travis-ci.org/vermiculus/magithub/jobs/384138493#L1112

Great! Subscribed to vermiculus/magithub#219 and will try again once
that has been fixed :)
